### ISSUE TITLE
Importing proto files from the same folder raises "File not found" error

### ISSUE THREAD

**Issue by rotomer** [protostuff/protobuf-jetbrains-plugin#68]
Great work on the plugin! 👍 

Starting from the last protobuf plugin version (v0.10.0) - there seems to be a false error on importing proto files from the same folder.

See attached image for a screenshot.
![proto](https://user-images.githubusercontent.com/7535448/28353706-9d8eaf1e-6c65-11e7-8022-c3114d51977b.png)

protoc runs successfully, and the build and tests run as expected.

Please let me know if there's a specific project configuration that is expected for the import validation to work.

Thanks,
Tomer R.

**Comment by kshchepanovskyi** [comment]
Hi @rotomer 

This issue has been fixed yesterday :) 
https://github.com/protostuff/protobuf-jetbrains-plugin/issues/66

Please upgrade plugin to version 0.10.1.

**Comment by rotomer** [comment]
Unfortunately, I'm afraid upgrading didn't solve the issue. 

If it helps the files are co-located on the same directory.

**Comment by kshchepanovskyi** [comment]
I think I know what's going on.

Please check folder structure where your proto files are stored. In general, it is similar to Java - if package is `common.api`, then proto file should be in folder `common/api`.

Plugin version 0.10.1 has a heuristic that detects source root (or include path, the one that you use with `protoc`'s `-I` option). 
It works in a following way: `common_messages.proto` has package `common.api`, so plugin assumes that the "source root" is two folders up (`src/main/protobuf/common/api/common_messages.proto` will result in `src/main/protobuf/`). But this assumption does not work, as file is inside of `src/main/protobuf`, and import is resolved to `src/common_fields.proto`.

There are two ways to fix folder structure:

1. Fix folder structure: move proto files to folders inside of `src/main/protobuf` that correspond to their `package` statements; change imports to correspond to new structure: `import "common_messages.proto"` -> `import "common/api/common_messages.proto"`.
2. Remove package statement.

Alternatively, you can mark `src/main/protobuf` as a source or resource root. If you are using maven, you can do it in `pom.xml` by adding this folder to resources.

**Comment by rotomer** [comment]
@kshchepanovskyi Thanks 😃 

I'll follow your suggestions and let you know how it fared.

**Comment by rotomer** [comment]
@kshchepanovskyi I gave the folder structure alternative a try, and it did solve the import validation error but then running protoc failed (via [this plugin](https://github.com/os72/protoc-jar-maven-plugin)).

Anyway, I resorted to keeping the existing simplistic folder structure and adding `src/main/protobuf` as a resource root to the maven pom file.

Now everything works 😃 

Thanks again,
Tomer R.
